### ISSUE TITLE
1. As a user, I want to read the names of all of the items in my shopping list

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/smart-shopping-list#4]
## Summary

The most important feature of our app is the ability to look at what's on the list, so the user knows what they need to buy. The `List` component is the best place in our code to do that. In fact, this feature is already partially implemented. Refer to the acceptance criteria in this issue, and the existing code, to understand the work that remains.

The `List` component is rendered on the `/list` page. Because the navigation links are currently broken, you'll have to type that path into your browser's address bar.

## Acceptance criteria
- [x] The `streamListItems` function is used in `App.jsx` to get the items in the current list from the Firestore database
- [x] The list is passed into the `List` component as a prop named `data`
- [ ] In `List.jsx`, the `ListItem` component is used to render the name of each item

## Notes
- ⚠️ Your **only goal** is to make sure that the names of the items render as expected. You might be tempted to modify `ListItem.jsx` to show more information – you will do that **later**. If you want a peek at the future, [this wireframe](https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-populated.png) is what your list could look like closer to the end of the project.
- The data you need is already being passed into the `List` component. What steps do you need to take in order to render it?

**Comment by stacietaylorcima** [comment]
**_Update: I went ahead and made these AC language changes cause I realized that is the format/language used in all the issues after number 2._** 

My initial thought is that the AC is very tutorial-like because it is giving explicit steps on how to do it, but I'm not mad at that. I wonder if we even just changed the language to be more AC-like and less TODO-list-like, if that would add a layer of complexity. 

*  The streamListItems function is used in App.jsx to get the items in the current list from the Firestore database
* The list of items is passed into the List component as a prop named data
* List.jsx uses the ListItem component to render the name of each item


I do love that this gives the explicit functions and components the Collabies will be working with though. On a real team, they'd probably be with another engineer who would be walking them through these things, so it seems more real and less go-figure-it-all-out-yourselves, which I like. Great work!

**Comment by thetrend** [comment]
Curriculum Revamp edit: (WIP)

_1. Collabies need to authenticate into the app prior to the db populating
2. Mentors need to seed the db with the collabies' user ids (with one shopping list)
3. Remove the `streamListItems` reference and change it to `useShoppingListData`_

## Title

1. As a user, I want to read the names of all of the items in my shopping list

## Summary

The most important feature of our app is the ability to look at what's on our lists, so the user knows what they need to buy. For this to work, we'll have to be able to choose a our shopping lists. The `List` and `Home` components are the best place in our code to do that. In fact, this feature is already partially implemented. Refer to the acceptance criteria in this issue, and the existing code, to understand the work that remains.

The `List` component is rendered on the `/list` page. Because the navigation links are currently broken, you'll have to type that path into your browser's address bar.

## Acceptance criteria
- [x] The `useShoppingLists` hook is used in `App.jsx` to get the shopping lists a user has access to from the database
- [x] The lists are passed into the `Home` component as a prop named `data`
- [x] The `setListPath` function is passed into the `Home` component so we can update the current list
- [x] The `useShoppingListData` hook is used in `App.jsx` to get the items in the current list from the Firestore database
- [x] The list is passed into the `List` component as a prop named `data`
- [ ] In `Home.jsx`, the `SingleList` component is used to render the name of each shopping list a user is subscribed to
- [ ] In `List.jsx`, the `ListItem` component is used to render the name of each item

## Notes
- ⚠️ Your **only goal** is to make sure that the names of the items render as expected. You might be tempted to modify `ListItem.jsx` or `SingleList.jsx` to show more information – you will do that **later**. If you want a peek at the future, [this wireframe](https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-populated.png) is what your list could look like closer to the end of the project.
- The data you need is already being passed into the `List` and `Home` components. What steps do you need to take in order to render it?
